### ISSUE TITLE
Refused to connect to 'https://raw.githubusercontent.com/davizinmakerkkj/PoopGPT/main/PoopGPT.txt' because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by imStoorm** [davizinmakerkkj/PoopGPT#1]
Refused to connect to 'https://raw.githubusercontent.com/davizinmakerkkj/PoopGPT/main/PoopGPT.txt' because it violates the following Content Security Policy directive: "connect-src 'self' statsigapi.net https://chat.openai.com wss://fp-async-webps-staging.webpubsub.azure.com *.oaiusercontent.com https://events.statsigapi.net api-js.mixpanel.com https://tcr9i.chat.openai.com fileserviceuploadsperm.blob.core.windows.net o33249.ingest.sentry.io wss://fp-async-webps-prod.webpubsub.azure.com https://featuregates.org https://oaistatic.com http://localhost:* https://*.oaistatic.com https://chatgpt.com api-iam.intercom.io https://*.chatgpt.com rum.browser-intake-datadoghq.com"

**Comment by Dfg-2k** [comment]
What did nationalism look like in Vietnam?

**Comment by davizinmakerkkj** [comment]
patched manually by OpenAI.
